/**
 * THALES (c)
 */
package org.obeonetwork.dsl.spem.uma.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import org.obeonetwork.dsl.spem.uma.util.UmaAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class UmaItemProviderAdapterFactory extends UmaAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public UmaItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.spem.uma.Artifact} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ArtifactItemProvider artifactItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.spem.uma.Artifact}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createArtifactAdapter() {
		if (artifactItemProvider == null) {
			artifactItemProvider = new ArtifactItemProvider(this);
		}

		return artifactItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.spem.uma.CapabilityPattern} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CapabilityPatternItemProvider capabilityPatternItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.spem.uma.CapabilityPattern}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCapabilityPatternAdapter() {
		if (capabilityPatternItemProvider == null) {
			capabilityPatternItemProvider = new CapabilityPatternItemProvider(this);
		}

		return capabilityPatternItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.spem.uma.Checklist} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ChecklistItemProvider checklistItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.spem.uma.Checklist}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createChecklistAdapter() {
		if (checklistItemProvider == null) {
			checklistItemProvider = new ChecklistItemProvider(this);
		}

		return checklistItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.spem.uma.Concept} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConceptItemProvider conceptItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.spem.uma.Concept}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createConceptAdapter() {
		if (conceptItemProvider == null) {
			conceptItemProvider = new ConceptItemProvider(this);
		}

		return conceptItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.spem.uma.CategoryPackage} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CategoryPackageItemProvider categoryPackageItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.spem.uma.CategoryPackage}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCategoryPackageAdapter() {
		if (categoryPackageItemProvider == null) {
			categoryPackageItemProvider = new CategoryPackageItemProvider(this);
		}

		return categoryPackageItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.spem.uma.CustomCategory} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CustomCategoryItemProvider customCategoryItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.spem.uma.CustomCategory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCustomCategoryAdapter() {
		if (customCategoryItemProvider == null) {
			customCategoryItemProvider = new CustomCategoryItemProvider(this);
		}

		return customCategoryItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.spem.uma.Deliverable} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DeliverableItemProvider deliverableItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.spem.uma.Deliverable}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDeliverableAdapter() {
		if (deliverableItemProvider == null) {
			deliverableItemProvider = new DeliverableItemProvider(this);
		}

		return deliverableItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.spem.uma.Process} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ProcessItemProvider processItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.spem.uma.Process}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createProcessAdapter() {
		if (processItemProvider == null) {
			processItemProvider = new ProcessItemProvider(this);
		}

		return processItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.spem.uma.DeliveryProcess} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DeliveryProcessItemProvider deliveryProcessItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.spem.uma.DeliveryProcess}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDeliveryProcessAdapter() {
		if (deliveryProcessItemProvider == null) {
			deliveryProcessItemProvider = new DeliveryProcessItemProvider(this);
		}

		return deliveryProcessItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.spem.uma.Discipline} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DisciplineItemProvider disciplineItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.spem.uma.Discipline}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDisciplineAdapter() {
		if (disciplineItemProvider == null) {
			disciplineItemProvider = new DisciplineItemProvider(this);
		}

		return disciplineItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.spem.uma.DisciplineGrouping} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DisciplineGroupingItemProvider disciplineGroupingItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.spem.uma.DisciplineGrouping}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDisciplineGroupingAdapter() {
		if (disciplineGroupingItemProvider == null) {
			disciplineGroupingItemProvider = new DisciplineGroupingItemProvider(this);
		}

		return disciplineGroupingItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.spem.uma.Root} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RootItemProvider rootItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.spem.uma.Root}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRootAdapter() {
		if (rootItemProvider == null) {
			rootItemProvider = new RootItemProvider(this);
		}

		return rootItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.spem.uma.Domain} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DomainItemProvider domainItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.spem.uma.Domain}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDomainAdapter() {
		if (domainItemProvider == null) {
			domainItemProvider = new DomainItemProvider(this);
		}

		return domainItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.spem.uma.EstimatingConsideration} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EstimatingConsiderationItemProvider estimatingConsiderationItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.spem.uma.EstimatingConsideration}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEstimatingConsiderationAdapter() {
		if (estimatingConsiderationItemProvider == null) {
			estimatingConsiderationItemProvider = new EstimatingConsiderationItemProvider(this);
		}

		return estimatingConsiderationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.spem.uma.Example} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExampleItemProvider exampleItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.spem.uma.Example}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExampleAdapter() {
		if (exampleItemProvider == null) {
			exampleItemProvider = new ExampleItemProvider(this);
		}

		return exampleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.spem.uma.Iteration} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IterationItemProvider iterationItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.spem.uma.Iteration}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIterationAdapter() {
		if (iterationItemProvider == null) {
			iterationItemProvider = new IterationItemProvider(this);
		}

		return iterationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.spem.uma.Outcome} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OutcomeItemProvider outcomeItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.spem.uma.Outcome}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOutcomeAdapter() {
		if (outcomeItemProvider == null) {
			outcomeItemProvider = new OutcomeItemProvider(this);
		}

		return outcomeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.spem.uma.Phase} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PhaseItemProvider phaseItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.spem.uma.Phase}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPhaseAdapter() {
		if (phaseItemProvider == null) {
			phaseItemProvider = new PhaseItemProvider(this);
		}

		return phaseItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.spem.uma.Practice} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PracticeItemProvider practiceItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.spem.uma.Practice}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPracticeAdapter() {
		if (practiceItemProvider == null) {
			practiceItemProvider = new PracticeItemProvider(this);
		}

		return practiceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.spem.uma.ProcessPlanningTemplate} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ProcessPlanningTemplateItemProvider processPlanningTemplateItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.spem.uma.ProcessPlanningTemplate}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createProcessPlanningTemplateAdapter() {
		if (processPlanningTemplateItemProvider == null) {
			processPlanningTemplateItemProvider = new ProcessPlanningTemplateItemProvider(this);
		}

		return processPlanningTemplateItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.spem.uma.Report} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ReportItemProvider reportItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.spem.uma.Report}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createReportAdapter() {
		if (reportItemProvider == null) {
			reportItemProvider = new ReportItemProvider(this);
		}

		return reportItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.spem.uma.ReusableAsset} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ReusableAssetItemProvider reusableAssetItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.spem.uma.ReusableAsset}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createReusableAssetAdapter() {
		if (reusableAssetItemProvider == null) {
			reusableAssetItemProvider = new ReusableAssetItemProvider(this);
		}

		return reusableAssetItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.spem.uma.Roadmap} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RoadmapItemProvider roadmapItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.spem.uma.Roadmap}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRoadmapAdapter() {
		if (roadmapItemProvider == null) {
			roadmapItemProvider = new RoadmapItemProvider(this);
		}

		return roadmapItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.spem.uma.Template} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TemplateItemProvider templateItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.spem.uma.Template}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTemplateAdapter() {
		if (templateItemProvider == null) {
			templateItemProvider = new TemplateItemProvider(this);
		}

		return templateItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.spem.uma.TermDefinition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TermDefinitionItemProvider termDefinitionItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.spem.uma.TermDefinition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTermDefinitionAdapter() {
		if (termDefinitionItemProvider == null) {
			termDefinitionItemProvider = new TermDefinitionItemProvider(this);
		}

		return termDefinitionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.spem.uma.ToolMentor} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ToolMentorItemProvider toolMentorItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.spem.uma.ToolMentor}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createToolMentorAdapter() {
		if (toolMentorItemProvider == null) {
			toolMentorItemProvider = new ToolMentorItemProvider(this);
		}

		return toolMentorItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.spem.uma.Whitepaper} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WhitepaperItemProvider whitepaperItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.spem.uma.Whitepaper}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createWhitepaperAdapter() {
		if (whitepaperItemProvider == null) {
			whitepaperItemProvider = new WhitepaperItemProvider(this);
		}

		return whitepaperItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.spem.uma.Guideline} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GuidelineItemProvider guidelineItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.spem.uma.Guideline}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGuidelineAdapter() {
		if (guidelineItemProvider == null) {
			guidelineItemProvider = new GuidelineItemProvider(this);
		}

		return guidelineItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.spem.uma.SupportingMaterial} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SupportingMaterialItemProvider supportingMaterialItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.spem.uma.SupportingMaterial}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSupportingMaterialAdapter() {
		if (supportingMaterialItemProvider == null) {
			supportingMaterialItemProvider = new SupportingMaterialItemProvider(this);
		}

		return supportingMaterialItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.spem.uma.RoleDefinitionPackage} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RoleDefinitionPackageItemProvider roleDefinitionPackageItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.spem.uma.RoleDefinitionPackage}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRoleDefinitionPackageAdapter() {
		if (roleDefinitionPackageItemProvider == null) {
			roleDefinitionPackageItemProvider = new RoleDefinitionPackageItemProvider(this);
		}

		return roleDefinitionPackageItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.spem.uma.TaskDefinitionPackage} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TaskDefinitionPackageItemProvider taskDefinitionPackageItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.spem.uma.TaskDefinitionPackage}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTaskDefinitionPackageAdapter() {
		if (taskDefinitionPackageItemProvider == null) {
			taskDefinitionPackageItemProvider = new TaskDefinitionPackageItemProvider(this);
		}

		return taskDefinitionPackageItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.spem.uma.WorkProductDefinitionPackage} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WorkProductDefinitionPackageItemProvider workProductDefinitionPackageItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.spem.uma.WorkProductDefinitionPackage}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createWorkProductDefinitionPackageAdapter() {
		if (workProductDefinitionPackageItemProvider == null) {
			workProductDefinitionPackageItemProvider = new WorkProductDefinitionPackageItemProvider(this);
		}

		return workProductDefinitionPackageItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.spem.uma.GuidancePackage} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GuidancePackageItemProvider guidancePackageItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.spem.uma.GuidancePackage}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGuidancePackageAdapter() {
		if (guidancePackageItemProvider == null) {
			guidancePackageItemProvider = new GuidancePackageItemProvider(this);
		}

		return guidancePackageItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.spem.uma.DisciplinePackage} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DisciplinePackageItemProvider disciplinePackageItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.spem.uma.DisciplinePackage}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDisciplinePackageAdapter() {
		if (disciplinePackageItemProvider == null) {
			disciplinePackageItemProvider = new DisciplinePackageItemProvider(this);
		}

		return disciplinePackageItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.spem.uma.DomainPackage} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DomainPackageItemProvider domainPackageItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.spem.uma.DomainPackage}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDomainPackageAdapter() {
		if (domainPackageItemProvider == null) {
			domainPackageItemProvider = new DomainPackageItemProvider(this);
		}

		return domainPackageItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.spem.uma.WorkProductKindPackage} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WorkProductKindPackageItemProvider workProductKindPackageItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.spem.uma.WorkProductKindPackage}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createWorkProductKindPackageAdapter() {
		if (workProductKindPackageItemProvider == null) {
			workProductKindPackageItemProvider = new WorkProductKindPackageItemProvider(this);
		}

		return workProductKindPackageItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.spem.uma.RoleSetPackage} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RoleSetPackageItemProvider roleSetPackageItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.spem.uma.RoleSetPackage}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRoleSetPackageAdapter() {
		if (roleSetPackageItemProvider == null) {
			roleSetPackageItemProvider = new RoleSetPackageItemProvider(this);
		}

		return roleSetPackageItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.spem.uma.ToolDefinitionPackage} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ToolDefinitionPackageItemProvider toolDefinitionPackageItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.spem.uma.ToolDefinitionPackage}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createToolDefinitionPackageAdapter() {
		if (toolDefinitionPackageItemProvider == null) {
			toolDefinitionPackageItemProvider = new ToolDefinitionPackageItemProvider(this);
		}

		return toolDefinitionPackageItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.spem.uma.ConfigurationPackage} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConfigurationPackageItemProvider configurationPackageItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.spem.uma.ConfigurationPackage}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createConfigurationPackageAdapter() {
		if (configurationPackageItemProvider == null) {
			configurationPackageItemProvider = new ConfigurationPackageItemProvider(this);
		}

		return configurationPackageItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.spem.uma.CapabilityPatternPackage} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CapabilityPatternPackageItemProvider capabilityPatternPackageItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.spem.uma.CapabilityPatternPackage}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCapabilityPatternPackageAdapter() {
		if (capabilityPatternPackageItemProvider == null) {
			capabilityPatternPackageItemProvider = new CapabilityPatternPackageItemProvider(this);
		}

		return capabilityPatternPackageItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.spem.uma.DeliveryProcessPackage} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DeliveryProcessPackageItemProvider deliveryProcessPackageItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.spem.uma.DeliveryProcessPackage}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDeliveryProcessPackageAdapter() {
		if (deliveryProcessPackageItemProvider == null) {
			deliveryProcessPackageItemProvider = new DeliveryProcessPackageItemProvider(this);
		}

		return deliveryProcessPackageItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.spem.uma.RoleSet} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RoleSetItemProvider roleSetItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.spem.uma.RoleSet}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRoleSetAdapter() {
		if (roleSetItemProvider == null) {
			roleSetItemProvider = new RoleSetItemProvider(this);
		}

		return roleSetItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.spem.uma.QualificationPackage} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected QualificationPackageItemProvider qualificationPackageItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.spem.uma.QualificationPackage}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createQualificationPackageAdapter() {
		if (qualificationPackageItemProvider == null) {
			qualificationPackageItemProvider = new QualificationPackageItemProvider(this);
		}

		return qualificationPackageItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.spem.uma.ProcessComponentPackage} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ProcessComponentPackageItemProvider processComponentPackageItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.spem.uma.ProcessComponentPackage}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createProcessComponentPackageAdapter() {
		if (processComponentPackageItemProvider == null) {
			processComponentPackageItemProvider = new ProcessComponentPackageItemProvider(this);
		}

		return processComponentPackageItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.spem.uma.WorkProductKind} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WorkProductKindItemProvider workProductKindItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.spem.uma.WorkProductKind}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createWorkProductKindAdapter() {
		if (workProductKindItemProvider == null) {
			workProductKindItemProvider = new WorkProductKindItemProvider(this);
		}

		return workProductKindItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (artifactItemProvider != null) artifactItemProvider.dispose();
		if (capabilityPatternItemProvider != null) capabilityPatternItemProvider.dispose();
		if (checklistItemProvider != null) checklistItemProvider.dispose();
		if (conceptItemProvider != null) conceptItemProvider.dispose();
		if (categoryPackageItemProvider != null) categoryPackageItemProvider.dispose();
		if (customCategoryItemProvider != null) customCategoryItemProvider.dispose();
		if (deliverableItemProvider != null) deliverableItemProvider.dispose();
		if (processItemProvider != null) processItemProvider.dispose();
		if (deliveryProcessItemProvider != null) deliveryProcessItemProvider.dispose();
		if (disciplineItemProvider != null) disciplineItemProvider.dispose();
		if (disciplineGroupingItemProvider != null) disciplineGroupingItemProvider.dispose();
		if (rootItemProvider != null) rootItemProvider.dispose();
		if (domainItemProvider != null) domainItemProvider.dispose();
		if (estimatingConsiderationItemProvider != null) estimatingConsiderationItemProvider.dispose();
		if (exampleItemProvider != null) exampleItemProvider.dispose();
		if (iterationItemProvider != null) iterationItemProvider.dispose();
		if (outcomeItemProvider != null) outcomeItemProvider.dispose();
		if (phaseItemProvider != null) phaseItemProvider.dispose();
		if (practiceItemProvider != null) practiceItemProvider.dispose();
		if (processPlanningTemplateItemProvider != null) processPlanningTemplateItemProvider.dispose();
		if (reportItemProvider != null) reportItemProvider.dispose();
		if (reusableAssetItemProvider != null) reusableAssetItemProvider.dispose();
		if (roadmapItemProvider != null) roadmapItemProvider.dispose();
		if (templateItemProvider != null) templateItemProvider.dispose();
		if (termDefinitionItemProvider != null) termDefinitionItemProvider.dispose();
		if (toolMentorItemProvider != null) toolMentorItemProvider.dispose();
		if (whitepaperItemProvider != null) whitepaperItemProvider.dispose();
		if (guidelineItemProvider != null) guidelineItemProvider.dispose();
		if (supportingMaterialItemProvider != null) supportingMaterialItemProvider.dispose();
		if (roleDefinitionPackageItemProvider != null) roleDefinitionPackageItemProvider.dispose();
		if (taskDefinitionPackageItemProvider != null) taskDefinitionPackageItemProvider.dispose();
		if (workProductDefinitionPackageItemProvider != null) workProductDefinitionPackageItemProvider.dispose();
		if (guidancePackageItemProvider != null) guidancePackageItemProvider.dispose();
		if (disciplinePackageItemProvider != null) disciplinePackageItemProvider.dispose();
		if (domainPackageItemProvider != null) domainPackageItemProvider.dispose();
		if (workProductKindPackageItemProvider != null) workProductKindPackageItemProvider.dispose();
		if (roleSetPackageItemProvider != null) roleSetPackageItemProvider.dispose();
		if (toolDefinitionPackageItemProvider != null) toolDefinitionPackageItemProvider.dispose();
		if (configurationPackageItemProvider != null) configurationPackageItemProvider.dispose();
		if (capabilityPatternPackageItemProvider != null) capabilityPatternPackageItemProvider.dispose();
		if (deliveryProcessPackageItemProvider != null) deliveryProcessPackageItemProvider.dispose();
		if (roleSetItemProvider != null) roleSetItemProvider.dispose();
		if (qualificationPackageItemProvider != null) qualificationPackageItemProvider.dispose();
		if (processComponentPackageItemProvider != null) processComponentPackageItemProvider.dispose();
		if (workProductKindItemProvider != null) workProductKindItemProvider.dispose();
	}

}
